### ISSUE TITLE
Improved behaviour of applyverbs.py

### ISSUE THREAD

**Issue by woody6402** [ryanprescott/realtek-verb-tools#3] opened 2021-06-26 09:32 UTC
in a recent sound kernel analyzes if was helpfull to add comments and empty lines to the verb file.
See attached code with very small changes applied by another contributor,
[applyverbs.py.txt](https://github.com/ryanprescott/realtek-verb-tools/files/6719886/applyverbs.py.txt)

**Comment by ryanprescott** [comment] 2021-10-01 23:25
Duplicate of Improved behaviour of applyverbs.py #4

**Closed as completed by ryanprescott** 2021-10-01 23:25 UTC
